#!/usr/bin/env bash

################################
# Dependencies:
# - ponymix
################################

dir=$(dirname $0)
source $dir/util.sh

full=""
short=""
status=0

step=${BLOCK_INSTANCE:-5}

getVolume() {
	ponymix get-volume
}

isMuted() {
	ponymix is-muted
}

case $BLOCK_BUTTON in
	# left click
	# mute/unmute
	1) pavucontrol >/dev/null ;;

	# right click
	# mute/unmute
	3) ponymix toggle >/dev/null ;;

	# scroll up
	# raise volume
	4) ponymix increase $step >/dev/null ;;

	# scroll down
	# lower volume
	5) ponymix decrease $step >/dev/null ;;
esac

vol=$(getVolume)

# determine mute status
if isMuted; then
	status=33
fi

full="VOL $vol% "
short=$vol

echo $full
echo $short
exit $status
